[package]
name = "parquet2lance"
version = "0.1.0"
edition = "2021"
description = "Convert parquet file to lance format."
license-file = "LICENSE"

[dependencies]
clap = { version = "4", features = ["derive"] }
arrow = { version = "35", features = ["prettyprint"]}
tokio = { version = "1", features = ["full"] }
arrow-array = "35"
lance = { git = "https://github.com/eto-ai/lance.git" }
parquet = "35"
