name: Python

on:
  push:
    branches:
    - main
    tags:
    - "*"
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
        - runner: ubuntu-latest
          target: x86_64
        - runner: ubuntu-latest
          target: armv7
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Build wheels
      uses: PyO3/maturin-action@v1
      with:
        working-directory: ./python
        target: ${{ matrix.platform.target }}
        args: --release --out dist --find-interpreter
        sccache: "true"
        manylinux: auto
