name: Rust

on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./rust
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler libssl-dev
    - run: cargo fmt --check
    - run: cargo clippy --all-features --all-targets --no-deps
    - run: cargo test
    - run: cargo build --all-features --release
