name: Rust

on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./rust
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust toolchain
      run: |
        rustup toolchain install nightly
        rustup default nightly
        rustup component add rustfmt clippy
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y protobuf-compiler libssl-dev
    - run: cargo fmt --check
    - run: cargo clippy --all-features --all-targets --no-deps
    - run: cargo test
    - run: cargo build --all-features --release
