name: Rust

on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
    branches:
    - main

jobs:
  build:
    defaults:
      run:
        working-directory: ./rust
    uses: haoxins/github-workflows/.github/workflows/rust.yaml@main
